version: "3.8"

services:
  woms-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6007:6007"
    environment:
      - ASPNETCORE_URLS=http://+:6007
    restart: unless-stopped